import { createHash, randomBytes, randomFillSync } from 'node:crypto';
import { connect as tlsConnect } from 'node:tls';
import { connect as netConnect } from 'node:net';
import { createServer as createHttpServer } from 'node:http';
import { createServer as createHttpsServer } from 'node:https';
import { deflateRawSync, inflateRawSync } from 'node:zlib';
export { GUID, CRLF, EMPTY, CLOSE_FRAME, CLOSE_FRAME_UNMASKED, PONG_EMPTY, PONG_EMPTY_UNMASKED, PING_EMPTY, PING_EMPTY_UNMASKED, DEFAULT_CIPHERS, ERR_CODES } from './lib/constants/index.mjs';
export { fastMask32, nextMask, mask32, pool, poolOff, POOL_SIZE, seed } from './lib/masking/index.mjs';
export { pack, packInto, frameLen, packHeader, parseFrames } from './lib/frame/index.mjs';
export { getHeaderBuf, returnHeaderBuf, getFragBuf, returnFragBuf, getFrameBuf, releaseFrameBuf, usePool, FRAME_POOL_SIZE, _framePool2, _framePool4, _framePool10, FRAG_POOL_SIZE, _fragPool } from './lib/buffer-pool/index.mjs';
export { makeCloseFrame, abortHandshake, computeAcceptKey } from './lib/handshake/index.mjs';
export { createHash, randomBytes, randomFillSync };
export { tlsConnect, netConnect };
export { createHttpServer, createHttpsServer };
export { deflateRawSync, inflateRawSync };
